#!/usr/bin/env sh

# #########
# Variables
# #########

BUSYBOX_VERSION="1.31.1"
BUSYBOX_URL="https://busybox.net/downloads/busybox-$BUSYBOX_VERSION.tar.bz2"

INIT_VERSION="0.2"
INIT_URL="https://git.carbslinux.org/archives/init/init-0.2.tar.gz"

# ########
# Messages
# ########

out() { printf "\033[1m\033[36m->\033[0;00m $1\\n" ;}
error() { printf "\033[1m\033[31m-> ERROR:\033[0;00m $1\\n" ;} >&2
die() { error "$1" ; exit 1 ;}
ask() { printf "\033[1;33m== $1 ==\\n(y/N) " ; read -r ans ; case "$ans" in [Yy]*) return 0 ;; *) return 1 ;; esac ;}

# Let's check that the user has root priviliges
# before starting anything. 
[ "$(id -u)" -eq 0 ] || die "You need root priviliges to run this script"


# Ask user for confirmation
out "This program will change the way your system behaves by completely\\n removing sysvinit and replacing it with busybox."
ask "Do you want to continue?" || die "User Exited"


# Read the explanation on install_busybox function

# install_savedconfig() {
# 	out "Making sure savedconfig directory exists"
# 	mkdir -p /etc/portage/savedconfig/sys-apps || return 1
# 	out "Installing saved config"
# 	cp -f busybox-config "/etc/portage/savedconfig/sys-apps/busybox-$BUSYBOX_VERSION" || die "Could not install saved config"
# 	out "Configuration Installed successfully"
# }
# 
# install_useflags() {
# 	out "Making sure package.use directory exists"
# 	[ -d /etc/portage/package.use ] || mkdir -p /etc/portage/package.use/ || return 1
# 	out "Writing busybox useflags to /etc/portage/package.use/busybox"
# 	printf "sys-apps/busybox savedconfig static\\n" > /etc/portage/package.use/busybox || return 1
# 	out "USE Flags set!"
# }

install_busybox() {
	# For some reason even with "savedconfig" Portage emerges
	# busybox with unspecified programs such as mkdir mount. We
	# don't want this as it will cause problems when unmerging.
	# Yeah, those important programs I have mentioned will be gone
	# unless you emerge them again. I am not taking that risk here.
	out "Fetching busybox"
	wget "$BUSYBOX_URL" || return 1
	out "Checking sha256sum of busybox"
	sha256sum -c busybox-checksum || die "Busybox checksum did not pass"
	out "Creating work/src directory for building busybox"
	mkdir -p work/src || die "Could not create work/src directory"
	tar xf busybox-$BUSYBOX_VERSION.tar.bz2 -C work/src --strip-components 1 || return 1
	out "Copying busybox-config and starting build"
	cp busybox-config work/src/.config
	make -C work/src || return 1
	out "Installing busybox to /usr/local/bin/busybox-init"
	make -C work/src install CONFIG_PREFIX="/usr/local" || return 1
	mv /usr/local/bin/busybox /usr/local/bin/busybox-init
}

remove_sysvinit() {
	out "Backing up sysvinit as a binary package so you can revert anytime."
	quickpkg --include-config y sysvinit || ask "Couldn't backup sysvinit, continue?" || return 1
	out "Removing sysvinit"
	emerge --unmerge sys-apps/sysvinit || die "Could not unmerge sysvinit"
}

install_initscripts() {
	out "Installing new inittab and init scripts"
	out "Getting Carbs Linux init scripts"
	wget "$INIT_URL"
	out "Checking sha256sum of carbs-init"
	sha256-sum -c init-checksum || die "carbs-init checksum did not pass"
	mkdir -p initscripts || die "Could not create initscripts directory"
	out "Extracting sources"
	tar xf "init-$INIT_VERSION.tar.gz" -C initscripts --strip-components 1 || return 1
	out "Applying patch for Gentoo"
	cd initscripts || return 1
	patch -p1 < ../gentoo_initscripts.patch || die "patch failed"
	cd .. || return 1
	make -C initscripts install || die "Could not install init scripts"
	out "Successfully installed initscripts"
}

busybox_install() {
	out "Install busybox applets (runit, init)"
	/usr/local/bin/busybox-init --install
	# We should do some sanity checks and report back
	for program in $(/usr/local/bin/busybox-init --list); do
		command -v "$program" || error "$program is not installed"
	done
}

# install_savedconfig || die "Could not install savedconfig"
# install_useflags || die "Could not install USE Flags"
install_busybox || die "Could not install busybox"
remove_sysvinit || die "Could not remove sysvinit"
install_initscripts || die "Could not install initscripts"
busybox_install || die "Could not successfully install busybox applets"
