#!/usr/bin/env sh

# #########
# Variables
# #########

BUSYBOX_VERSION="1.30.1"

# ########
# Messages
# ########

out() { printf "\033[1m\033[36m->\033[0;00m $1\\n" ;}
error() { printf "\033[1m\033[31m-> ERROR:\033[0;00m $1\\n" ;} >&2
die() { error "$1" ; exit 1 ;}
ask() { printf "\033[1;33m== $1 ==\\n(y/N) " ; read -r ans ; case "$ans" in [Yy]*) return 0 ;; *) return 1 ;; esac ;}

# Let's check that the user has root priviliges
# before starting anything. 
[ "$(id -u)" -eq 0 ] || die "You need root priviliges to run this script"


# Ask user for confirmation
out "This program will change the way your system behaves by completely\\n removing sysvinit and replacing it with busybox."
ask "Do you want to continue?" || die "User Exited"


install_savedconfig() {
	out "Making sure savedconfig directory exists"
	mkdir -p /etc/portage/savedconfig/sys-apps || return 1
	out "Installing saved config"
	cp -f busybox-config "/etc/portage/savedconfig/sys-apps/busybox-$BUSYBOX_VERSION" || die "Could not install saved config"
	out "Configuration Installed successfully"
}

install_useflags() {
	out "Making sure package.use directory exists"
	[ -d /etc/portage/package.use ] || mkdir -p /etc/portage/package.use/ || return 1
	out "Writing busybox useflags to /etc/portage/package.use/busybox"
	printf "sys-apps/busybox savedconfig static\\n" > /etc/portage/package.use/busybox || return 1
	out "USE Flags set!"
}

install_busybox() {
	out "Emerging busybox"
	emerge --newuse sys-apps/busybox || die "Could not emerge busybox"
}

remove_sysvinit() {
	out "Backing up sysvinit as a binary package so you can revert anytime."
	quickpkg --include-config y sysvinit || ask "Couldn't backup sysvinit, continue?" || return 1
	out "Removing sysvinit"
	emerge --unmerge sys-apps/sysvinit || die "Could not unmerge sysvinit"
}

install_initscripts() {
	out "Installing new inittab and init scripts"
	make -C initscripts install || die "Could not install init scripts"
}

busybox_install() {
	out "Install busybox applets (runit, init)"
	/bin/busybox --install
	# We should do some sanity checks and report back
	for program in $(busybox --list); do
		command -v "$program" || error "$program is not installed"
	done
}

install_savedconfig || die "Could not install savedconfig"
install_useflags || die "Could not install USE Flags"
install_busybox || die "Could not install busybox"
remove_sysvinit || die "Could not remove sysvinit"
install_initscripts || die "Could not install initscripts"
busybox_install || die "Could not successfully install busybox applets"
